runtime: php74
service: default
instance_class: B1
manual_scaling:
  instances: 1

handlers:
- url: /dist
  static_dir: dist

- url: /plugins
  static_dir: plugins

- url: /(.+\.(ico|jpg|png|gif))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif))$

- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$

- url: /pages/(.+\.php)$
  script: /pages/\1

- url: /pages/forms/(.+\.php)$
  script: /pages/forms/\1

- url: /(.+\.php)$
  script: \1

# - url: /conf/(.+\.php)$
#   script: /conf/\1

# - url: /.*
#  script: auto
#  login: admin

#- url: /(.+\.php)$
#  script: auto
#  login: admin


env_variables:
 # GOOGLE_STORAGE_BUCKET: ""
 # populate these to use the "mysql" or "postres" backends
 CLOUDSQL_CONNECTION_NAME: css-unite:asia-southeast2:cssunite01
 CLOUDSQL_USER: root
 CLOUDSQL_PASSWORD: password
 CLOUDSQL_DATABASE_NAME: css_order

 # TCP domain socket setup; uncomment if using a TCP domain socket
 # INSTANCE_HOST: 34.128.85.44


# Choose to enable either a TCP or Unix domain socket for your database
# connection:
# Enable a Unix domain socket:
# beta_settings:
#  cloud_sql_instances: "css-unite:asia-southeast2:cssunite01=tcp:5432"

# Enable a TCP domain socket:
beta_settings:
 cloud_sql_instances: "css-unite:asia-southeast2:cssunite01=tcp:3306"



# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
entrypoint: serve handlers.php



